/* Escape from Barbi Blue: the house kit's definitions, the one place where the sizes and names of its pieces live.
   The game reads it (js/layout.js places the solid furniture by these footprints, js/kit.js loads the models by these names), and so does
   Blender (tools/blender/kit/defs.py json.loads the text between the markers, so it stays strict JSON: no comments, no trailing commas).
   Metres, Blender axes (z up, the front faces -y). A game unit u is 0.045 m (a tile, T = 50 u, is 2.25 m).
   items: the furniture you bump into, one per solidIds entry. d.solids[k] means solidIds[k], so ids are only ever added at the end.
     slot   pocket: centred on a corner point inside a hall (box at most 22 x 22 u); bar: between two of them, along the grid line (22 x 72 u);
            wall: at a corner point on a hall wall, its back flush with the wall (22 u across, 13..61 u deep);
            island: a whole tile inside a hall (28..43.3 u a side; ins = its inset from the tile's edges in u, [x, y], 3.33..11)
     w, d   the box: round(m / 0.045) u, w across the slot and d along its depth (islands unrotated: w along x, d along y)
     h, occ the box height, and whom it hides: tall = everyone from her, low = only a crouching player, none. occ is given per piece
            (a bed's head or a dress form is high but too thin to hide behind), so it doesn't always follow h.
     vars   how many looks (d.solids' v); var: overrides per look (the taller crate stack). rooms: the HALL_PLAN templates that may use it.
     node   the model; nodes, when there are several: one per look (_v<n>) or per ceiling height (_H<cm>, from hcm; kit.js picks the room's)
     top    the model's top, when something rises above the box (a tool rack, a propped lid, a flue that runs on past the ceiling)
     fix    the light fixture it carries, at its <node>_fix empty. anim: one of anims, turning the child named <node> + pivot.
     tris   the triangle budget (hi tier; trisLo for lo)
   band, fixtures, arch, wardrobes: the pieces you can't bump into. W along the wall, D out into the room, H up, z0 the bottom,
     R how far back into the wall tile it goes. fit 'max': an envelope the model stays inside; otherwise it matches within 0.02 m.
     mount  wall: origin on the wall plane at floor level. floor, surface: at the footprint's centre, at the bottom. ceiling: on the ceiling,
            hanging down. face: replaces a whole 2.25 m wall face from the floor to faceH (with uv1). practical: inside its furniture.
            doorway: at the doorway tile's centre, across the passage. hinge: on the hinge axis at the leaf's bottom, the leaf along +x.
     Sizes in arch: open = a window's opening [w, h, sill]; door, hole, niche: an opening's [w, h(, depth)]; post, lining, head, hinge,
     breast, mantel, porch: the doorway, fireplace and exit measures of the build spec (A9.3, B5).
     Wall pieces reach out at most 0.44 m and stay within W 2.025 m (u 0.05..0.95 of the face), except those in a corner.
     Wardrobes keep level.js's: carcass 1.15 x 0.60 x 2.25 m, crown at most 2.35, leaves 0.575 x 2.2 from 0.025 m up, hinged at
     x = +-0.575, y = -0.305 (three.js z = 0.305), the origin on the hinge at the leaf's bottom; coats only beyond x = +-clearX.
   Changing a footprint (slot, w, d, ins) or an occ means bumping version (houses from another version are refused); new fields bump nothing. */
'use strict';
const KIT = /*KITDEFS*/{ "version": 1, "u": 0.045, "styles": ["wood", "tile", "concrete", "attic", "workshop"],
  "solidIds": [
    "crib", "iron_bed", "rocking_chair", "toy_chest", "doll_house", "rocking_horse", "pram", "nursery_table", "column_tile", "display_bench",
    "plinth_bust", "vitrine_double", "brick_pier", "stanchion", "shelf_rack", "boiler_wall", "chest_freezer", "crate_stack", "truss_post", "sheet_chair",
    "sheet_tall", "sheet_sofa", "steamer_trunk", "chimney_breast", "iron_bed_sheeted", "workbench", "kiln", "drying_rack", "sewing_table", "dress_form",
    "steel_column", "isl_crib_rocker", "isl_twin_cribs", "isl_bed_screen", "isl_tea_party", "isl_dollhouse", "isl_washstand", "isl_dining",
    "isl_grand_piano", "isl_parlour", "isl_reading", "isl_boiler", "isl_shelving_double", "isl_crate_stack", "isl_washtubs", "isl_wine_rack",
    "isl_sheeted_sofa", "isl_trunk_pile", "isl_servant_bed", "isl_toy_circle", "isl_sheeted_armoire", "isl_dress_forms", "isl_workbench_double",
    "isl_kiln", "isl_drying_rack", "isl_sorting_table", "isl_office_desk", "isl_hanging_dolls"
  ],
  "items": {
    "crib": { "style": "wood", "slot": "wall", "w": 0.72, "d": 1.3, "h": 1.05, "occ": "none", "vars": 2, "rooms": ["nursery_dormitory", "night_nursery"],
        "node": "Solid_crib", "nodes": ["Solid_crib_v0", "Solid_crib_v1"], "anim": "mobile", "tris": 6000,
        "notes": "slats, chipped paint, stained cloth mattress, a turning mobile over it; head to the wall" },
    "iron_bed": { "style": "wood", "slot": "wall", "w": 0.95, "d": 2, "h": 1.1, "occ": "none", "vars": 1, "rooms": ["nursery_dormitory", "night_nursery"],
        "node": "Solid_iron_bed", "tris": 12000, "notes": "iron bedstead, cloth sheet (hero); head to the wall" },
    "rocking_chair": { "style": "wood", "slot": "pocket", "w": 0.66, "d": 0.95, "h": 1.1, "occ": "none", "vars": 1,
        "rooms": ["nursery_dormitory", "night_nursery", "playroom", "washroom"],
        "node": "Solid_rocking_chair", "anim": "rock", "tris": 5000, "notes": "rocks inside its box at full swing" },
    "toy_chest": { "style": "wood", "slot": "pocket", "w": 0.9, "d": 0.5, "h": 0.6, "occ": "none", "vars": 2, "rooms": ["playroom", "nursery_dormitory", "schoolroom"],
        "node": "Solid_toy_chest", "nodes": ["Solid_toy_chest_v0", "Solid_toy_chest_v1"], "tris": 5000, "notes": "lid ajar" },
    "doll_house": { "style": "wood", "slot": "pocket", "w": 0.95, "d": 0.6, "h": 1.3, "occ": "low", "vars": 1, "rooms": ["playroom"],
        "node": "Solid_doll_house", "tris": 5000 },
    "rocking_horse": { "style": "wood", "slot": "pocket", "w": 0.99, "d": 0.42, "h": 0.9, "occ": "none", "vars": 1, "rooms": ["playroom", "schoolroom"],
        "node": "Solid_rocking_horse", "tris": 5000 },
    "pram": { "style": "wood", "slot": "pocket", "w": 0.6, "d": 0.99, "h": 1.05, "occ": "low", "vars": 1, "rooms": ["nursery_dormitory", "night_nursery", "playroom"],
        "node": "Solid_pram", "tris": 5000 },
    "nursery_table": { "style": "wood", "slot": "bar", "w": 0.85, "d": 2.6, "h": 0.62, "occ": "none", "vars": 1, "rooms": ["schoolroom", "playroom"],
        "node": "Solid_nursery_table", "tris": 5000, "notes": "long low table, small chairs inside the box" },
    "column_tile": { "style": "tile", "slot": "pocket", "w": 0.66, "d": 0.66, "h": 3.5, "occ": "tall", "vars": 1,
        "rooms": ["gallery", "colonnade", "dining_room", "parlour", "library"],
        "node": "Col_column_tile", "nodes": ["Col_column_tile_H350", "Col_column_tile_H400", "Col_column_tile_H450"], "hcm": [350, 400, 450], "tris": 3000,
        "notes": "marble column, base and capital; reaches the ceiling (kit.js picks the node for the ceiling height)" },
    "display_bench": { "style": "tile", "slot": "bar", "w": 0.7, "d": 3.1, "h": 1.25, "occ": "low", "vars": 1, "rooms": ["gallery"],
        "node": "Solid_display_bench", "tris": 12000, "notes": "glass domes over baked dolls (hero)" },
    "plinth_bust": { "style": "tile", "slot": "pocket", "w": 0.6, "d": 0.6, "h": 1.45, "occ": "low", "vars": 1, "rooms": ["gallery", "dining_room", "parlour", "library"],
        "node": "Solid_plinth_bust", "tris": 5000, "notes": "plinth with a bust under a bell jar" },
    "vitrine_double": { "style": "tile", "slot": "bar", "w": 0.99, "d": 2, "h": 1.95, "occ": "tall", "vars": 1, "rooms": ["dining_room", "library", "parlour"],
        "node": "Solid_vitrine_double", "tris": 5000, "notes": "back-to-back glass vitrines" },
    "brick_pier": { "style": "concrete", "slot": "pocket", "w": 0.7, "d": 0.7, "h": 2.7, "occ": "tall", "vars": 1, "rooms": ["boiler_room", "storage", "wine_cellar", "coal_store"],
        "node": "Col_brick_pier", "nodes": ["Col_brick_pier_H270", "Col_brick_pier_H300", "Col_brick_pier_H330"], "hcm": [270, 300, 330], "tris": 3000 },
    "stanchion": { "style": "concrete", "slot": "pocket", "w": 0.3, "d": 0.3, "h": 3, "occ": "none", "vars": 1, "rooms": ["storage", "laundry", "workroom", "boiler_room"],
        "node": "Col_stanchion", "nodes": ["Col_stanchion_H300", "Col_stanchion_H330"], "hcm": [300, 330], "tris": 3000, "notes": "steel prop with a jack head under a beam plate" },
    "shelf_rack": { "style": "concrete", "slot": "bar", "w": 0.6, "d": 3.1, "h": 2, "occ": "tall", "vars": 1, "rooms": ["storage", "workroom", "wine_cellar"],
        "node": "Solid_shelf_rack", "tris": 12000, "notes": "jars, tins (hero)" },
    "boiler_wall": { "style": "concrete", "slot": "wall", "w": 0.99, "d": 1.4, "h": 1.9, "occ": "tall", "vars": 1, "rooms": ["boiler_room", "laundry"],
        "node": "Solid_boiler_wall", "top": 3.4, "fix": "boiler_glow", "tris": 5000,
        "notes": "back to the wall; the flue rises past the highest basement ceiling (3.3), hidden above it" },
    "chest_freezer": { "style": "concrete", "slot": "pocket", "w": 0.99, "d": 0.66, "h": 0.88, "occ": "none", "vars": 1, "rooms": ["storage", "laundry", "workroom"],
        "node": "Solid_chest_freezer", "tris": 5000 },
    "crate_stack": { "style": "concrete", "slot": "pocket", "w": 0.9, "d": 0.9, "h": 1, "occ": "none", "vars": 2, "var": [{}, { "h": 1.6, "occ": "low" }],
        "rooms": ["storage", "coal_store", "workroom", "wine_cellar"],
        "node": "Solid_crate_stack", "nodes": ["Solid_crate_stack_v0", "Solid_crate_stack_v1"], "tris": 5000, "notes": "v0 (A) two crates 1.0 m, v1 (B) three crates 1.6 m" },
    "truss_post": { "style": "attic", "slot": "pocket", "w": 0.25, "d": 0.25, "h": 2.6, "occ": "none", "vars": 1,
        "rooms": ["truss_hall", "storeroom", "servants_dormitory", "sheet_room"],
        "node": "Solid_truss_post", "tris": 5000, "notes": "timber post up to the hall truss tie at 2.60 (B5)" },
    "sheet_chair": { "style": "attic", "slot": "pocket", "w": 0.95, "d": 0.95, "h": 1.1, "occ": "low", "vars": 2, "rooms": ["sheet_room", "storeroom", "box_room", "hideout"],
        "node": "Solid_sheet_chair", "nodes": ["Solid_sheet_chair_v0", "Solid_sheet_chair_v1"], "tris": 5000, "notes": "armchair under a cloth sheet" },
    "sheet_tall": { "style": "attic", "slot": "pocket", "w": 0.99, "d": 0.7, "h": 1.95, "occ": "tall", "vars": 2, "rooms": ["sheet_room", "storeroom"],
        "node": "Solid_sheet_tall", "nodes": ["Solid_sheet_tall_v0", "Solid_sheet_tall_v1"], "tris": 5000, "notes": "tall cabinet under a cloth sheet" },
    "sheet_sofa": { "style": "attic", "slot": "bar", "w": 0.95, "d": 2.2, "h": 0.95, "occ": "none", "vars": 1, "rooms": ["sheet_room", "storeroom", "truss_hall"],
        "node": "Solid_sheet_sofa", "tris": 5000, "notes": "sofa under a cloth sheet" },
    "steamer_trunk": { "style": "attic", "slot": "pocket", "w": 0.95, "d": 0.55, "h": 0.65, "occ": "none", "vars": 2, "rooms": ["box_room", "storeroom", "hideout", "truss_hall"],
        "node": "Solid_steamer_trunk", "nodes": ["Solid_steamer_trunk_v0", "Solid_steamer_trunk_v1"], "tris": 5000 },
    "chimney_breast": { "style": "attic", "slot": "pocket", "w": 0.99, "d": 0.99, "h": 4, "occ": "tall", "vars": 1, "rooms": ["truss_hall", "hideout", "servants_dormitory"],
        "node": "Col_chimney_breast", "nodes": ["Col_chimney_breast_H400"], "hcm": [400], "tris": 3000,
        "notes": "brick stack; one height that passes through every attic roof slope (ridge 3.9 at most), hidden above it" },
    "iron_bed_sheeted": { "style": "attic", "slot": "wall", "w": 0.95, "d": 2, "h": 1, "occ": "none", "vars": 1, "rooms": ["servants_dormitory", "hideout"],
        "node": "Solid_iron_bed_sheeted", "tris": 5000, "notes": "iron bed under a dust sheet; head to the wall" },
    "workbench": { "style": "workshop", "slot": "bar", "w": 0.85, "d": 3.1, "h": 0.92, "occ": "low", "vars": 1,
        "rooms": ["assembly_floor", "casting_hall", "paint_room", "parts_store"],
        "node": "Solid_workbench", "top": 1.6, "fix": "anglepoise", "tris": 12000, "notes": "vices, doll limbs, eye trays, tool rack to 1.6 m (hero)" },
    "kiln": { "style": "workshop", "slot": "pocket", "w": 0.99, "d": 0.99, "h": 1.75, "occ": "tall", "vars": 1, "rooms": ["kiln_room", "casting_hall"],
        "node": "Solid_kiln", "top": 4.6, "fix": "kiln_glow", "tris": 5000, "notes": "the flue rises past the highest workshop ceiling (4.5), hidden above it" },
    "drying_rack": { "style": "workshop", "slot": "bar", "w": 0.6, "d": 3, "h": 2, "occ": "tall", "vars": 1, "rooms": ["paint_room", "casting_hall", "kiln_room"],
        "node": "Solid_drying_rack", "tris": 5000, "notes": "porcelain limbs drying" },
    "sewing_table": { "style": "workshop", "slot": "pocket", "w": 0.95, "d": 0.55, "h": 1.15, "occ": "low", "vars": 1,
        "rooms": ["assembly_floor", "paint_room", "office", "eye_room"],
        "node": "Solid_sewing_table", "tris": 5000 },
    "dress_form": { "style": "workshop", "slot": "pocket", "w": 0.5, "d": 0.5, "h": 1.65, "occ": "none", "vars": 1, "rooms": ["assembly_floor", "paint_room", "parts_store"],
        "node": "Solid_dress_form", "tris": 5000 },
    "steel_column": { "style": "workshop", "slot": "pocket", "w": 0.3, "d": 0.3, "h": 3.6, "occ": "none", "vars": 1,
        "rooms": ["assembly_floor", "casting_hall", "kiln_room", "parts_store"],
        "node": "Col_steel_column", "nodes": ["Col_steel_column_H360", "Col_steel_column_H420", "Col_steel_column_H450"], "hcm": [360, 420, 450], "tris": 3000 },
    "isl_crib_rocker": { "style": "wood", "slot": "island", "w": 1.4, "d": 1.75, "h": 1.1, "occ": "none", "ins": [9.5, 5.5], "vars": 1,
        "rooms": ["nursery_dormitory", "night_nursery"],
        "node": "Isl_crib_rocker", "anim": "rock_set", "tris": 25000, "trisLo": 6000, "notes": "crib + rocking chair + round rug" },
    "isl_twin_cribs": { "style": "wood", "slot": "island", "w": 1.4, "d": 1.85, "h": 1.05, "occ": "none", "ins": [9.5, 4.5], "vars": 1,
        "rooms": ["nursery_dormitory", "night_nursery"],
        "node": "Isl_twin_cribs", "top": 1.8, "anim": "mobile", "tris": 25000, "trisLo": 6000, "notes": "2 cribs, a mobile turning at 1.55 m over its own box" },
    "isl_bed_screen": { "style": "wood", "slot": "island", "w": 1.95, "d": 1.45, "h": 1.65, "occ": "low", "ins": [3.5, 9], "vars": 1,
        "rooms": ["nursery_dormitory", "night_nursery"],
        "node": "Isl_bed_screen", "tris": 25000, "trisLo": 6000, "notes": "bed + 3-panel screen" },
    "isl_tea_party": { "style": "wood", "slot": "island", "w": 1.5, "d": 1.4, "h": 0.95, "occ": "none", "ins": [8.5, 9.5], "vars": 1, "rooms": ["playroom", "schoolroom"],
        "node": "Isl_tea_party", "tris": 25000, "trisLo": 6000, "notes": "table, 4 baked seated dolls (not scare dolls)" },
    "isl_dollhouse": { "style": "wood", "slot": "island", "w": 1.6, "d": 1.3, "h": 1.45, "occ": "low", "ins": [7, 10.5], "vars": 1, "rooms": ["playroom", "schoolroom"],
        "node": "Isl_dollhouse", "tris": 25000, "trisLo": 6000, "notes": "big dollhouse on a rug with toys" },
    "isl_washstand": { "style": "wood", "slot": "island", "w": 1.4, "d": 1.3, "h": 1.1, "occ": "none", "ins": [9.5, 10.5], "vars": 1, "rooms": ["washroom"],
        "node": "Isl_washstand", "tris": 25000, "trisLo": 6000, "notes": "tin bath + washstand" },
    "isl_dining": { "style": "tile", "slot": "island", "w": 1.95, "d": 1.45, "h": 1.1, "occ": "none", "ins": [3.5, 9], "vars": 1, "rooms": ["dining_room"],
        "node": "Isl_dining", "fix": "candelabrum", "tris": 25000, "trisLo": 6000, "notes": "table + 6 chairs, candelabrum" },
    "isl_grand_piano": { "style": "tile", "slot": "island", "w": 1.5, "d": 1.95, "h": 1.25, "occ": "low", "ins": [8.5, 3.5], "vars": 1, "rooms": ["parlour"],
        "node": "Isl_grand_piano", "top": 1.9, "tris": 25000, "trisLo": 6000, "notes": "lid propped open to 1.9 m" },
    "isl_parlour": { "style": "tile", "slot": "island", "w": 1.9, "d": 1.6, "h": 1.1, "occ": "none", "ins": [4, 7], "vars": 1, "rooms": ["parlour"],
        "node": "Isl_parlour", "fix": "standard_lamp", "tris": 25000, "trisLo": 6000, "notes": "round table, 2 armchairs, standard lamp" },
    "isl_reading": { "style": "tile", "slot": "island", "w": 1.9, "d": 1.3, "h": 1.2, "occ": "none", "ins": [4, 10.5], "vars": 1, "rooms": ["library"],
        "node": "Isl_reading", "tris": 25000, "trisLo": 6000, "notes": "table, chair, globe" },
    "isl_boiler": { "style": "concrete", "slot": "island", "w": 1.9, "d": 1.5, "h": 1.9, "occ": "tall", "ins": [4, 8.5], "vars": 1, "rooms": ["boiler_room"],
        "node": "Isl_boiler", "top": 3.4, "fix": "boiler_glow", "tris": 25000, "trisLo": 6000, "notes": "the flue rises past the highest basement ceiling (3.3), hidden above it" },
    "isl_shelving_double": { "style": "concrete", "slot": "island", "w": 1.85, "d": 1.3, "h": 2, "occ": "tall", "ins": [4.5, 10.5], "vars": 1, "rooms": ["storage", "workroom"],
        "node": "Isl_shelving_double", "tris": 25000, "trisLo": 6000, "notes": "back-to-back shelving + crates" },
    "isl_crate_stack": { "style": "concrete", "slot": "island", "w": 1.6, "d": 1.3, "h": 1.5, "occ": "low", "ins": [7, 10.5], "vars": 1,
        "rooms": ["storage", "coal_store", "workroom"],
        "node": "Isl_crate_stack", "tris": 25000, "trisLo": 6000 },
    "isl_washtubs": { "style": "concrete", "slot": "island", "w": 1.8, "d": 1.3, "h": 1.4, "occ": "low", "ins": [5, 10.5], "vars": 1, "rooms": ["laundry"],
        "node": "Isl_washtubs", "tris": 25000, "trisLo": 6000, "notes": "tubs + mangle" },
    "isl_wine_rack": { "style": "concrete", "slot": "island", "w": 1.85, "d": 1.3, "h": 1.9, "occ": "tall", "ins": [4.5, 10.5], "vars": 1, "rooms": ["wine_cellar"],
        "node": "Isl_wine_rack", "tris": 25000, "trisLo": 6000 },
    "isl_sheeted_sofa": { "style": "attic", "slot": "island", "w": 1.9, "d": 1.3, "h": 1.2, "occ": "tall", "ins": [4, 10.5], "vars": 1, "rooms": ["sheet_room", "truss_hall"],
        "node": "Isl_sheeted_sofa", "top": 1.9, "tris": 25000, "trisLo": 6000, "notes": "sheeted sofa with a sheeted clock to 1.9 m" },
    "isl_trunk_pile": { "style": "attic", "slot": "island", "w": 1.7, "d": 1.3, "h": 1.3, "occ": "low", "ins": [6, 10.5], "vars": 1,
        "rooms": ["box_room", "storeroom", "truss_hall"],
        "node": "Isl_trunk_pile", "fix": "hurricane_lantern", "tris": 25000, "trisLo": 6000 },
    "isl_servant_bed": { "style": "attic", "slot": "island", "w": 1.9, "d": 1.4, "h": 1, "occ": "none", "ins": [4, 9.5], "vars": 1, "rooms": ["servants_dormitory"],
        "node": "Isl_servant_bed", "tris": 25000, "trisLo": 6000 },
    "isl_toy_circle": { "style": "attic", "slot": "island", "w": 1.7, "d": 1.7, "h": 0.4, "occ": "none", "ins": [6, 6], "vars": 1, "rooms": ["hideout"],
        "node": "Isl_toy_circle", "tris": 25000, "trisLo": 6000, "notes": "ring of toys, the photograph from note 4-4; toys at the ring ends reach 0.40 m" },
    "isl_sheeted_armoire": { "style": "attic", "slot": "island", "w": 1.3, "d": 1.3, "h": 2, "occ": "tall", "ins": [10.5, 10.5], "vars": 1,
        "rooms": ["sheet_room", "storeroom", "box_room"],
        "node": "Isl_sheeted_armoire", "tris": 25000, "trisLo": 6000 },
    "isl_dress_forms": { "style": "attic", "slot": "island", "w": 1.6, "d": 1.3, "h": 1.65, "occ": "low", "ins": [7, 10.5], "vars": 1, "rooms": ["sheet_room", "truss_hall"],
        "node": "Isl_dress_forms", "tris": 25000, "trisLo": 6000 },
    "isl_workbench_double": { "style": "workshop", "slot": "island", "w": 1.9, "d": 1.3, "h": 0.92, "occ": "low", "ins": [4, 10.5], "vars": 1,
        "rooms": ["assembly_floor", "casting_hall", "eye_room"],
        "node": "Isl_workbench_double", "fix": "anglepoise", "tris": 25000, "trisLo": 6000, "notes": "doll in a vice" },
    "isl_kiln": { "style": "workshop", "slot": "island", "w": 1.4, "d": 1.3, "h": 1.7, "occ": "tall", "ins": [9.5, 10.5], "vars": 1, "rooms": ["kiln_room", "casting_hall"],
        "node": "Isl_kiln", "top": 4.6, "fix": "kiln_glow", "tris": 25000, "trisLo": 6000, "notes": "the flue rises past the highest workshop ceiling (4.5), hidden above it" },
    "isl_drying_rack": { "style": "workshop", "slot": "island", "w": 1.8, "d": 1.3, "h": 1.9, "occ": "tall", "ins": [5, 10.5], "vars": 1,
        "rooms": ["paint_room", "kiln_room", "casting_hall"],
        "node": "Isl_drying_rack", "tris": 25000, "trisLo": 6000 },
    "isl_sorting_table": { "style": "workshop", "slot": "island", "w": 1.8, "d": 1.3, "h": 0.95, "occ": "none", "ins": [5, 10.5], "vars": 1,
        "rooms": ["eye_room", "parts_store", "assembly_floor"],
        "node": "Isl_sorting_table", "tris": 25000, "trisLo": 6000, "notes": "trays of eyes" },
    "isl_office_desk": { "style": "workshop", "slot": "island", "w": 1.7, "d": 1.3, "h": 1.1, "occ": "none", "ins": [6, 10.5], "vars": 1, "rooms": ["office"],
        "node": "Isl_office_desk", "tris": 25000, "trisLo": 6000, "notes": "ledger, safe" },
    "isl_hanging_dolls": { "style": "workshop", "slot": "island", "w": 1.6, "d": 1.3, "h": 2.1, "occ": "tall", "ins": [7, 10.5], "vars": 1,
        "rooms": ["assembly_floor", "paint_room", "parts_store"],
        "node": "Isl_hanging_dolls", "anim": "sway", "tris": 25000, "trisLo": 6000, "notes": "dolls hang from a rail over the set only" }
  },
  "anims": {
    "rock": { "pivot": "_RockPivot", "axis": "x", "amp": 0.1, "period": 3.6 },
    "rock_set": { "pivot": "_RockPivot", "axis": "x", "amp": 0.12, "period": 3.6 },
    "mobile": { "pivot": "_MobilePivot", "axis": "z", "period": 24 },
    "pendulum": { "pivot": "_Pendulum", "axis": "y", "amp": 0.1, "period": 2 },
    "sway": { "pivot": "_SwayPivot", "axis": "x", "amp": 0.05, "period": 4.5 },
    "morph": { "keys": 2, "period": 5 }
  },
  "band": {
    "dresser": { "style": "wood", "mount": "wall", "W": 1, "D": 0.44, "H": 0.95, "node": "Band_dresser", "fix": "night_light", "tris": 4000 },
    "toy_shelf": { "style": "wood", "mount": "wall", "W": 1.2, "D": 0.3, "H": 1.6, "node": "Band_toy_shelf", "tris": 4000 },
    "changing_table": { "style": "wood", "mount": "wall", "W": 0.9, "D": 0.44, "H": 0.95, "node": "Band_changing_table", "tris": 4000 },
    "washstand": { "style": "wood", "mount": "wall", "W": 0.85, "D": 0.44, "H": 0.8, "node": "Band_washstand", "tris": 4000 },
    "radiator": { "style": "wood", "mount": "wall", "W": 0.8, "D": 0.12, "H": 0.65, "node": "Band_radiator", "tris": 4000, "notes": "under windows" },
    "bookshelf_low": { "style": "wood", "mount": "wall", "W": 0.9, "D": 0.32, "H": 1.1, "node": "Band_bookshelf_low", "tris": 4000 },
    "puppet_theatre": { "style": "wood", "mount": "wall", "W": 1.2, "D": 0.4, "H": 1.6, "node": "Band_puppet_theatre", "tris": 4000 },
    "night_stand": { "style": "wood", "mount": "wall", "W": 0.45, "D": 0.4, "H": 0.6, "node": "Band_night_stand", "tris": 4000 },
    "wall_clock": { "style": "wood", "mount": "wall", "W": 0.35, "D": 0.12, "H": 0.5, "z0": 1.75, "fit": "max", "node": "Band_wall_clock", "tris": 1500, "trisLo": 400 },
    "kids_frames": { "style": "wood", "mount": "wall", "W": 0.45, "D": 0.05, "H": 0.55, "z0": 1.25, "fit": "max", "node": "Band_kids_frames", "vars": 3,
        "nodes": ["Band_kids_frames_v0", "Band_kids_frames_v1", "Band_kids_frames_v2"], "tris": 1500, "trisLo": 400, "notes": "children's framed pictures, 3 kinds" },
    "coat_hooks": { "style": "wood", "mount": "wall", "W": 0.9, "D": 0.3, "H": 1, "z0": 0.75, "fit": "max", "node": "Band_coat_hooks", "tris": 4000,
        "notes": "hook rail at 1.7 m with a few coats hanging" },
    "doll_shelf": { "style": "wood", "mount": "wall", "W": 1.2, "D": 0.22, "H": 0.2, "z0": 1.27, "fit": "max", "node": "Band_doll_shelf", "tris": 4000,
        "notes": "shelf top at 1.45 m; seated scare dolls come from makeDoll at SOCKET empties" },
    "console": { "style": "tile", "mount": "wall", "W": 1, "D": 0.4, "H": 0.85, "node": "Band_console", "tris": 4000, "notes": "console table; hang console_mirror above it" },
    "console_mirror": { "style": "tile", "mount": "wall", "W": 0.8, "D": 0.06, "H": 0.95, "z0": 1, "fit": "max", "node": "Band_console_mirror", "tris": 4000,
        "notes": "dark mirror over the console" },
    "grandfather_clock": { "style": "tile", "mount": "wall", "W": 0.5, "D": 0.3, "H": 2.1, "node": "Band_grandfather_clock", "anim": "pendulum", "tris": 4000 },
    "doll_cabinet": { "style": "tile", "mount": "wall", "W": 1.2, "D": 0.42, "H": 2, "node": "Band_doll_cabinet", "tris": 4000, "notes": "glass front, baked dolls (hero)" },
    "china_cabinet": { "style": "tile", "mount": "wall", "W": 1.1, "D": 0.42, "H": 2, "node": "Band_china_cabinet", "tris": 4000 },
    "sideboard": { "style": "tile", "mount": "wall", "W": 1.6, "D": 0.44, "H": 0.95, "node": "Band_sideboard", "tris": 4000 },
    "hall_bench": { "style": "tile", "mount": "wall", "W": 1.2, "D": 0.42, "H": 0.48, "node": "Band_hall_bench", "tris": 4000 },
    "gilt_mirror": { "style": "tile", "mount": "wall", "W": 0.7, "D": 0.08, "H": 1, "z0": 1, "fit": "max", "node": "Band_gilt_mirror", "tris": 4000 },
    "umbrella_stand": { "style": "tile", "mount": "wall", "W": 0.35, "D": 0.35, "H": 0.95, "fit": "max", "node": "Band_umbrella_stand", "tris": 1500, "trisLo": 400 },
    "fuse_box": { "style": "concrete", "mount": "wall", "W": 0.45, "D": 0.18, "H": 0.55, "z0": 1.45, "fit": "max", "node": "Band_fuse_box", "tris": 1500, "trisLo": 400 },
    "water_heater": { "style": "concrete", "mount": "wall", "W": 0.42, "D": 0.42, "H": 1.6, "node": "Band_water_heater", "tris": 4000, "notes": "cylinder" },
    "utility_sink": { "style": "concrete", "mount": "wall", "W": 0.6, "D": 0.44, "H": 1.1, "fit": "max", "node": "Band_utility_sink", "tris": 4000,
        "notes": "sink 0.6 x 0.44 on legs, taps" },
    "pegboard": { "style": "concrete", "mount": "wall", "W": 1.2, "D": 0.15, "H": 0.9, "z0": 0.95, "fit": "max", "node": "Band_pegboard", "tris": 4000 },
    "coal_bin": { "style": "concrete", "mount": "wall", "W": 0.9, "D": 0.44, "H": 0.8, "fit": "max", "node": "Band_coal_bin", "tris": 4000 },
    "metal_shelf": { "style": "concrete", "mount": "wall", "W": 1.2, "D": 0.4, "H": 1.9, "node": "Band_metal_shelf", "tris": 4000 },
    "barrel": { "style": "concrete", "mount": "wall", "W": 0.42, "D": 0.42, "H": 0.62, "fit": "max", "node": "Band_barrel", "tris": 4000, "notes": "diameter 0.42" },
    "box_stack": { "style": "attic", "mount": "wall", "W": 0.9, "D": 0.44, "H": 1.2, "node": "Band_box_stack", "tris": 4000 },
    "rolled_rug": { "style": "attic", "mount": "wall", "W": 0.4, "D": 0.4, "H": 1.7, "fit": "max", "node": "Band_rolled_rug", "tris": 4000, "notes": "leaning against the wall" },
    "leaning_mirror": { "style": "attic", "mount": "wall", "W": 0.7, "D": 0.3, "H": 1.6, "fit": "max", "node": "Band_leaning_mirror", "tris": 4000 },
    "suitcase_pile": { "style": "attic", "mount": "wall", "W": 0.8, "D": 0.44, "H": 0.9, "fit": "max", "node": "Band_suitcase_pile", "tris": 4000 },
    "mannequin": { "style": "attic", "mount": "wall", "W": 0.42, "D": 0.42, "H": 1.75, "fit": "max", "node": "Band_mannequin", "tris": 4000, "notes": "diameter 0.42" },
    "frames_leaning": { "style": "attic", "mount": "wall", "W": 1.1, "D": 0.22, "H": 0.95, "fit": "max", "node": "Band_frames_leaning", "tris": 4000 },
    "cobweb_card": { "style": "attic", "mount": "corner", "W": 0.6, "D": 0.44, "H": 0.5, "z0": 2.2, "fit": "max", "node": "Band_cobweb_card", "tris": 1500, "trisLo": 400,
        "notes": "alpha card across a top corner, reaching at most 0.44 m from either wall; the u range rule does not apply to corners" },
    "eye_shelf": { "style": "workshop", "mount": "wall", "W": 1.3, "D": 0.3, "H": 1.9, "node": "Band_eye_shelf", "tris": 4000, "notes": "glossy jars of eyes" },
    "tool_wall": { "style": "workshop", "mount": "wall", "W": 1.6, "D": 0.2, "H": 1.2, "z0": 0.8, "fit": "max", "node": "Band_tool_wall", "tris": 4000 },
    "parts_drawers": { "style": "workshop", "mount": "wall", "W": 1, "D": 0.44, "H": 1.3, "node": "Band_parts_drawers", "tris": 4000 },
    "limb_hooks": { "style": "workshop", "mount": "wall", "W": 1.2, "D": 0.35, "H": 1, "z0": 1, "fit": "max", "node": "Band_limb_hooks", "tris": 4000,
        "notes": "doll limbs on hooks; replaces the hanging dolls of house.js" },
    "paint_shelf": { "style": "workshop", "mount": "wall", "W": 1.2, "D": 0.35, "H": 1.8, "node": "Band_paint_shelf", "tris": 4000 },
    "filing_cabinet": { "style": "workshop", "mount": "wall", "W": 0.45, "D": 0.44, "H": 1.3, "node": "Band_filing_cabinet", "tris": 4000 },
    "head_shelf": { "style": "workshop", "mount": "wall", "W": 1.6, "D": 0.26, "H": 0.75, "z0": 1.22, "fit": "max", "node": "Band_head_shelf", "tris": 4000,
        "notes": "two shelves of doll heads (1.30, 1.78 m); replaces the InstancedMesh of house.js" },
    "service_shelf": { "style": "common", "mount": "wall", "W": 1.4, "D": 0.25, "H": 1.8, "node": "Band_service_shelf", "tris": 4000, "notes": "servant runs" },
    "bell_board": { "style": "common", "mount": "wall", "W": 0.9, "D": 0.12, "H": 0.6, "z0": 1.9, "fit": "max", "node": "Band_bell_board", "tris": 4000,
        "notes": "servant runs and the F2 servants hall" },
    "conduit": { "style": "common", "mount": "wall", "W": 2, "D": 0.06, "H": 0.4, "z0": 2.1, "fit": "max", "node": "Band_conduit", "tris": 1500, "trisLo": 400,
        "notes": "servant runs" }
  },
  "fixtures": {
    "sconce_shade": { "style": "wood", "mount": "wall", "W": 0.3, "D": 0.25, "H": 0.4, "z0": 1.8, "fit": "max", "node": "Fix_sconce_shade", "emit": "Fix_sconce_shade_emit",
        "tris": 4000, "notes": "pink pleated shade; back plate centred at 1.95 m" },
    "pendant_shade": { "style": "wood", "mount": "ceiling", "W": 0.45, "D": 0.45, "H": 0.35, "z0": -0.35, "fit": "max", "node": "Fix_pendant_shade",
        "emit": "Fix_pendant_shade_emit", "tris": 4000, "notes": "hall pendant; the cord from the ceiling is drawn in JS" },
    "night_light": { "style": "wood", "mount": "surface", "W": 0.15, "D": 0.15, "H": 0.25, "fit": "max", "node": "Fix_night_light", "emit": "Fix_night_light_emit", "flicker": true,
        "tris": 4000, "notes": "stands on dressers" },
    "sconce_candles": { "style": "tile", "mount": "wall", "W": 0.35, "D": 0.22, "H": 0.45, "z0": 1.75, "fit": "max", "node": "Fix_sconce_candles", "emit": "Fix_sconce_candles_emit",
        "tris": 4000, "notes": "brass, 2 candles" },
    "chandelier": { "style": "tile", "mount": "ceiling", "W": 0.9, "D": 0.9, "H": 0.8, "z0": -0.8, "fit": "max", "node": "Fix_chandelier", "emit": "Fix_chandelier_emit",
        "tris": 4000, "notes": "crystal drops; bottom at 2.80 m or higher, so only under ceilings of 3.6 m or more" },
    "standard_lamp": { "style": "tile", "mount": "floor", "W": 0.45, "D": 0.45, "H": 1.6, "fit": "max", "node": "Fix_standard_lamp", "emit": "Fix_standard_lamp_emit", "tris": 4000,
        "notes": "stands in isl_parlour; steady" },
    "bulkhead": { "style": "concrete", "mount": "wall", "W": 0.22, "D": 0.15, "H": 0.3, "z0": 1.95, "fit": "max", "node": "Fix_bulkhead", "emit": "Fix_bulkhead_emit", "tris": 4000,
        "notes": "caged, centred at 2.1 m" },
    "bare_bulb": { "style": "concrete", "mount": "ceiling", "W": 0.08, "D": 0.08, "H": 0.16, "z0": -0.16, "fit": "max", "node": "Fix_bare_bulb", "emit": "Fix_bare_bulb_emit",
        "tris": 4000, "notes": "holder and bulb; cord drawn in JS (drop = min(0.63, ceiling - 2.35))" },
    "bulb_batten": { "style": "attic", "mount": "ceiling", "W": 0.12, "D": 0.12, "H": 0.18, "z0": -0.18, "fit": "max", "node": "Fix_bulb_batten", "emit": "Fix_bulb_batten_emit",
        "tris": 4000, "notes": "bulb on a batten holder" },
    "hurricane_lantern": { "style": "attic", "mount": "surface", "W": 0.2, "D": 0.2, "H": 0.35, "fit": "max", "node": "Fix_hurricane_lantern", "emit": "Fix_hurricane_lantern_emit",
        "flicker": true, "tris": 4000, "notes": "stands on a trunk" },
    "green_shade": { "style": "workshop", "mount": "ceiling", "W": 0.45, "D": 0.45, "H": 0.3, "z0": -0.3, "fit": "max", "node": "Fix_green_shade", "emit": "Fix_green_shade_emit",
        "tris": 4000, "notes": "enamel shade, diameter 0.45; cord drawn in JS" },
    "anglepoise": { "style": "workshop", "mount": "surface", "W": 0.3, "D": 0.55, "H": 0.7, "fit": "max", "node": "Fix_anglepoise", "emit": "Fix_anglepoise_emit", "tris": 4000,
        "notes": "on benches" },
    "boiler_glow": { "style": "concrete", "mount": "practical", "W": 0.35, "D": 0.1, "H": 0.25, "fit": "max", "node": "Fix_boiler_glow", "emit": "Fix_boiler_glow_emit",
        "tris": 4000, "notes": "firebox glow inside boiler_wall and isl_boiler" },
    "kiln_glow": { "style": "workshop", "mount": "practical", "W": 0.4, "D": 0.1, "H": 0.3, "fit": "max", "node": "Fix_kiln_glow", "emit": "Fix_kiln_glow_emit", "tris": 4000,
        "notes": "ember glow inside kiln and isl_kiln" },
    "fire_embers": { "style": "common", "mount": "practical", "W": 0.55, "D": 0.3, "H": 0.15, "fit": "max", "node": "Fix_fire_embers", "emit": "Fix_fire_embers_emit",
        "flicker": true, "tris": 4000, "notes": "in every fireplace firebox" },
    "candelabrum": { "style": "tile", "mount": "surface", "W": 0.35, "D": 0.15, "H": 0.45, "fit": "max", "node": "Fix_candelabrum", "emit": "Fix_candelabrum_emit", "flicker": true,
        "tris": 4000, "notes": "on the isl_dining table" },
    "batten_light": { "style": "common", "mount": "ceiling", "W": 0.6, "D": 0.1, "H": 0.08, "z0": -0.08, "fit": "max", "node": "Fix_batten_light", "emit": "Fix_batten_light_emit",
        "tris": 4000, "notes": "servant runs, flush with the ceiling" }
  },
  "arch": { "faceH": 3.0,
    "trims": {
      "wood": { "skirting": { "h": 0.18, "d": 0.025 }, "dado": 0.93, "cornice": { "h": 0.14, "d": 0.12 }, "pictureRail": 3, "notes": "ogee skirting; the dado rail sits on the rail baked into the wall texture" },
      "tile": { "skirting": { "h": 0.25 }, "dado": 0.87, "cornice": { "h": 0.2 }, "pictureRail": 3, "notes": "marble skirting" },
      "concrete": { "skirting": { "h": 0.1, "d": 0.04 }, "notes": "concrete curb" },
      "attic": { "skirting": { "h": 0.09, "d": 0.02 }, "notes": "plain board" },
      "workshop": { "skirting": { "h": 0.14 }, "dado": 0.93, "notes": "board skirting, rail, timber cornice" }
    },
    "pieces": {
      "Door_frame_wood": { "kind": "door_frame", "style": "wood", "mount": "doorway", "W": 2.25, "D": 0.4, "H": 2.66, "fit": "max", "post": 0.11, "lining": 0.34, "head": 2.6,
          "tris": 2000, "notes": "painted pine, 4-panel, finger marks (hero)" },
      "Door_leaf_wood": { "kind": "door_leaf", "style": "wood", "mount": "hinge", "W": 1, "D": 0.045, "H": 2.55, "hinge": 1.015, "tris": 2500,
          "notes": "mirrored in JS for the other leaf" },
      "Door_closed_wood": { "kind": "door_closed", "style": "wood", "mount": "face", "W": 2.25, "D": 0.05, "R": 0.1, "H": 3, "fit": "max", "door": [0.9, 2.1], "uv1": true,
          "tris": 5000, "notes": "panelled door" },
      "Exit_wood": { "kind": "exit", "style": "wood", "mount": "face", "W": 2.25, "D": 0.1, "R": 1.2, "H": 3, "fit": "max", "uv1": true, "tris": 15000,
          "children": ["Exit_leaf_wood", "Exit_boards_wood", "Exit_lamp_wood"], "post": 0.63, "head": 2.4, "leaf": [1.15, 2.3], "porch": 1,
          "notes": "leaf hinged on the wall plane, swings out to 1.75 rad; SkyPlane behind; boards, chains" },
      "Door_frame_tile": { "kind": "door_frame", "style": "tile", "mount": "doorway", "W": 2.25, "D": 0.4, "H": 2.66, "fit": "max", "post": 0.11, "lining": 0.34, "head": 2.6,
          "tris": 2000, "notes": "mahogany, 6-panel (hero)" },
      "Door_leaf_tile": { "kind": "door_leaf", "style": "tile", "mount": "hinge", "W": 1, "D": 0.045, "H": 2.55, "hinge": 1.015, "tris": 2500,
          "notes": "mirrored in JS for the other leaf" },
      "Door_closed_tile": { "kind": "door_closed", "style": "tile", "mount": "face", "W": 2.25, "D": 0.05, "R": 0.1, "H": 3, "fit": "max", "door": [0.9, 2.1], "uv1": true,
          "tris": 5000, "notes": "panelled door" },
      "Exit_tile": { "kind": "exit", "style": "tile", "mount": "face", "W": 2.25, "D": 0.1, "R": 1.2, "H": 3, "fit": "max", "uv1": true, "tris": 15000,
          "children": ["Exit_leaf_tile", "Exit_boards_tile", "Exit_lamp_tile"], "post": 0.63, "head": 2.4, "leaf": [1.15, 2.3], "porch": 1,
          "notes": "leaf hinged on the wall plane, swings out to 1.75 rad; SkyPlane behind; boards, chains" },
      "Door_frame_concrete": { "kind": "door_frame", "style": "concrete", "mount": "doorway", "W": 2.25, "D": 0.4, "H": 2.66, "fit": "max", "post": 0.11, "lining": 0.34,
          "head": 2.6, "tris": 2000, "notes": "ledged-and-braced planks" },
      "Door_leaf_concrete": { "kind": "door_leaf", "style": "concrete", "mount": "hinge", "W": 1, "D": 0.045, "H": 2.55, "hinge": 1.015, "tris": 2500,
          "notes": "mirrored in JS for the other leaf" },
      "Door_closed_concrete": { "kind": "door_closed", "style": "concrete", "mount": "face", "W": 2.25, "D": 0.05, "R": 0.1, "H": 3, "fit": "max", "door": [0.9, 2.1], "uv1": true,
          "tris": 5000, "notes": "steel fire door" },
      "Exit_concrete": { "kind": "exit", "style": "concrete", "mount": "face", "W": 2.25, "D": 0.1, "R": 1.2, "H": 3, "fit": "max", "uv1": true, "tris": 15000,
          "children": ["Exit_leaf_concrete", "Exit_boards_concrete", "Exit_lamp_concrete"], "post": 0.63, "head": 2.4, "leaf": [1.15, 2.3], "porch": 1,
          "notes": "leaf hinged on the wall plane, swings out to 1.75 rad; SkyPlane behind; boards, chains" },
      "Door_frame_attic": { "kind": "door_frame", "style": "attic", "mount": "doorway", "W": 2.25, "D": 0.4, "H": 2.66, "fit": "max", "post": 0.11, "lining": 0.34, "head": 2.6,
          "tris": 2000, "notes": "boards, strap hinges" },
      "Door_leaf_attic": { "kind": "door_leaf", "style": "attic", "mount": "hinge", "W": 1, "D": 0.045, "H": 2.55, "hinge": 1.015, "tris": 2500,
          "notes": "mirrored in JS for the other leaf" },
      "Door_closed_attic": { "kind": "door_closed", "style": "attic", "mount": "face", "W": 2.25, "D": 0.05, "R": 0.1, "H": 3, "fit": "max", "door": [0.9, 2.1], "uv1": true,
          "tris": 5000, "notes": "hatch" },
      "Exit_attic": { "kind": "exit", "style": "attic", "mount": "face", "W": 2.25, "D": 0.1, "R": 1.2, "H": 3, "fit": "max", "uv1": true, "tris": 15000,
          "children": ["Exit_leaf_attic", "Exit_boards_attic", "Exit_lamp_attic"], "post": 0.63, "head": 2.4, "leaf": [1.15, 2.3], "porch": 1,
          "notes": "leaf hinged on the wall plane, swings out to 1.75 rad; SkyPlane behind; boards, chains" },
      "Door_frame_workshop": { "kind": "door_frame", "style": "workshop", "mount": "doorway", "W": 2.25, "D": 0.4, "H": 2.66, "fit": "max", "post": 0.11, "lining": 0.34,
          "head": 2.6, "tris": 2000, "notes": "half-glazed, wired glass" },
      "Door_leaf_workshop": { "kind": "door_leaf", "style": "workshop", "mount": "hinge", "W": 1, "D": 0.045, "H": 2.55, "hinge": 1.015, "tris": 2500,
          "notes": "mirrored in JS for the other leaf" },
      "Door_closed_workshop": { "kind": "door_closed", "style": "workshop", "mount": "face", "W": 2.25, "D": 0.05, "R": 0.1, "H": 3, "fit": "max", "door": [0.9, 2.1], "uv1": true,
          "tris": 5000, "notes": "panelled door" },
      "Exit_workshop": { "kind": "exit", "style": "workshop", "mount": "face", "W": 2.25, "D": 0.1, "R": 1.2, "H": 3, "fit": "max", "uv1": true, "tris": 15000,
          "children": ["Exit_leaf_workshop", "Exit_boards_workshop", "Exit_lamp_workshop"], "post": 0.63, "head": 2.4, "leaf": [1.15, 2.3], "porch": 1,
          "notes": "leaf hinged on the wall plane, swings out to 1.75 rad; SkyPlane behind; boards, chains" },
      "Win_sash": { "kind": "window", "style": "wood", "mount": "face", "W": 2.25, "D": 0.2, "R": 0.35, "H": 3, "fit": "max", "open": [1.1, 1.85, 0.8], "uv1": true,
          "children": ["Win_sash_frame", "Win_sash_glass", "Win_sash_sky", "Win_sash_curtain"], "tris": 10000, "notes": "sash window, lace + velvet drapes" },
      "Win_tall": { "kind": "window", "style": "tile", "mount": "face", "W": 2.25, "D": 0.2, "R": 0.35, "H": 3, "fit": "max", "open": [1.2, 2.05, 0.55], "uv1": true,
          "children": ["Win_tall_frame", "Win_tall_glass", "Win_tall_sky", "Win_tall_curtain"], "tris": 10000, "notes": "shutters, pelmet (in _curtain)" },
      "Win_cellar": { "kind": "window", "style": "concrete", "mount": "face", "W": 2.25, "D": 0.2, "R": 0.35, "H": 3, "fit": "max", "open": [0.9, 0.45, 2.05], "uv1": true,
          "children": ["Win_cellar_frame", "Win_cellar_glass", "Win_cellar_sky"], "tris": 10000,
          "notes": "bars, light well (well_alpha on the sky plane); for ceilings of 2.9 m and more" },
      "Win_cellar_short": { "kind": "window", "style": "concrete", "mount": "face", "W": 2.25, "D": 0.2, "R": 0.35, "H": 3, "fit": "max", "open": [0.9, 0.45, 1.9], "uv1": true,
          "children": ["Win_cellar_short_frame", "Win_cellar_short_glass", "Win_cellar_short_sky"], "tris": 10000, "notes": "head at 2.35 m, for ceilings under 2.9 m" },
      "Win_dormer": { "kind": "window", "style": "attic", "mount": "face", "W": 2.25, "D": 0.2, "R": 0.35, "H": 3, "fit": "max", "open": [0.7, 1, 1], "uv1": true,
          "children": ["Win_dormer_frame", "Win_dormer_glass", "Win_dormer_sky", "Win_dormer_curtain"], "tris": 10000, "notes": "dormer casement" },
      "Win_oculus": { "kind": "window", "style": "attic", "mount": "face", "W": 2.25, "D": 0.2, "R": 0.35, "H": 3, "fit": "max", "open": [0.8, 0.8, 1.4], "uv1": true,
          "children": ["Win_oculus_frame", "Win_oculus_glass", "Win_oculus_sky"], "tris": 10000, "notes": "round, diameter 0.8" },
      "Win_industrial": { "kind": "window", "style": "workshop", "mount": "face", "W": 2.25, "D": 0.2, "R": 0.35, "H": 3, "fit": "max", "open": [1.8, 1.9, 0.9], "uv1": true,
          "children": ["Win_industrial_frame", "Win_industrial_glass", "Win_industrial_sky", "Win_industrial_curtain"], "anim": "morph", "tris": 10000,
          "notes": "steel, 3 panes broken; the curtain has 2 shape keys (sway)" },
      "Mod_skylight_attic": { "kind": "skylight", "style": "attic", "mount": "ceiling", "W": 2.25, "D": 2.25, "H": 0.6, "fit": "max", "uv1": true, "tris": 3000,
          "notes": "replaces a ceiling tile; shaft lining 0.6 m; 2 per truss_hall" },
      "Mod_skylight_workshop": { "kind": "skylight", "style": "workshop", "mount": "ceiling", "W": 2.25, "D": 2.25, "H": 0.6, "fit": "max", "uv1": true, "tris": 3000,
          "notes": "sawtooth north light; 3 per assembly_floor" },
      "Mod_fireplace_wood": { "kind": "fireplace", "style": "wood", "mount": "face", "W": 2.25, "D": 0.42, "R": 0.45, "H": 3, "fit": "max", "uv1": true, "fix": "fire_embers",
          "breast": 0.4, "mantel": 1.25, "tris": 12000, "notes": "painted surround" },
      "Mod_fireplace_tile": { "kind": "fireplace", "style": "tile", "mount": "face", "W": 2.25, "D": 0.42, "R": 0.45, "H": 3, "fit": "max", "uv1": true, "fix": "fire_embers",
          "breast": 0.4, "mantel": 1.25, "tris": 12000, "notes": "marble" },
      "Mod_fireplace_workshop": { "kind": "fireplace", "style": "workshop", "mount": "face", "W": 2.25, "D": 0.42, "R": 0.45, "H": 3, "fit": "max", "uv1": true,
          "fix": "fire_embers", "breast": 0.4, "mantel": 1.25, "tris": 12000, "notes": "forge variant" },
      "Mod_wallhole_lath_A_wood": { "kind": "wallhole", "style": "wood", "mount": "face", "W": 2.25, "D": 0.35, "R": 0.12, "H": 3, "fit": "max", "uv1": true, "hole": [0.6, 0.45],
          "tris": 4000, "notes": "lath, horsehair plaster" },
      "Mod_wallhole_lath_B_wood": { "kind": "wallhole", "style": "wood", "mount": "face", "W": 2.25, "D": 0.35, "R": 0.12, "H": 3, "fit": "max", "uv1": true, "hole": [1, 0.8],
          "tris": 4000, "notes": "lath, horsehair plaster" },
      "Mod_wallhole_lath_C_wood": { "kind": "wallhole", "style": "wood", "mount": "face", "W": 2.25, "D": 0.35, "R": 0.12, "H": 3, "fit": "max", "uv1": true, "hole": [0.7, 0.5],
          "tris": 4000, "notes": "lath, horsehair plaster" },
      "Mod_wallhole_lath_A_tile": { "kind": "wallhole", "style": "tile", "mount": "face", "W": 2.25, "D": 0.35, "R": 0.12, "H": 3, "fit": "max", "uv1": true, "hole": [0.6, 0.45],
          "tris": 4000, "notes": "lath, horsehair plaster" },
      "Mod_wallhole_lath_B_tile": { "kind": "wallhole", "style": "tile", "mount": "face", "W": 2.25, "D": 0.35, "R": 0.12, "H": 3, "fit": "max", "uv1": true, "hole": [1, 0.8],
          "tris": 4000, "notes": "lath, horsehair plaster" },
      "Mod_wallhole_lath_C_tile": { "kind": "wallhole", "style": "tile", "mount": "face", "W": 2.25, "D": 0.35, "R": 0.12, "H": 3, "fit": "max", "uv1": true, "hole": [0.7, 0.5],
          "tris": 4000, "notes": "lath, horsehair plaster" },
      "Mod_wallhole_lath_A_workshop": { "kind": "wallhole", "style": "workshop", "mount": "face", "W": 2.25, "D": 0.35, "R": 0.12, "H": 3, "fit": "max", "uv1": true,
          "hole": [0.6, 0.45], "tris": 4000, "notes": "lath, horsehair plaster" },
      "Mod_wallhole_lath_B_workshop": { "kind": "wallhole", "style": "workshop", "mount": "face", "W": 2.25, "D": 0.35, "R": 0.12, "H": 3, "fit": "max", "uv1": true,
          "hole": [1, 0.8], "tris": 4000, "notes": "lath, horsehair plaster" },
      "Mod_wallhole_lath_C_workshop": { "kind": "wallhole", "style": "workshop", "mount": "face", "W": 2.25, "D": 0.35, "R": 0.12, "H": 3, "fit": "max", "uv1": true,
          "hole": [0.7, 0.5], "tris": 4000, "notes": "lath, horsehair plaster" },
      "Mod_breach_brick_A_concrete": { "kind": "wallhole", "style": "concrete", "mount": "face", "W": 2.25, "D": 0.35, "R": 0.12, "H": 3, "fit": "max", "uv1": true,
          "hole": [0.6, 0.45], "tris": 4000, "notes": "broken brick" },
      "Mod_breach_brick_B_concrete": { "kind": "wallhole", "style": "concrete", "mount": "face", "W": 2.25, "D": 0.35, "R": 0.12, "H": 3, "fit": "max", "uv1": true,
          "hole": [1, 0.8], "tris": 4000, "notes": "broken brick" },
      "Mod_breach_brick_C_concrete": { "kind": "wallhole", "style": "concrete", "mount": "face", "W": 2.25, "D": 0.35, "R": 0.12, "H": 3, "fit": "max", "uv1": true,
          "hole": [0.7, 0.5], "tris": 4000, "notes": "broken brick" },
      "Mod_hole_boards_A_attic": { "kind": "wallhole", "style": "attic", "mount": "face", "W": 2.25, "D": 0.35, "R": 0.12, "H": 3, "fit": "max", "uv1": true, "hole": [0.6, 0.45],
          "tris": 4000, "notes": "broken boards" },
      "Mod_hole_boards_B_attic": { "kind": "wallhole", "style": "attic", "mount": "face", "W": 2.25, "D": 0.35, "R": 0.12, "H": 3, "fit": "max", "uv1": true, "hole": [1, 0.8],
          "tris": 4000, "notes": "broken boards" },
      "Mod_hole_boards_C_attic": { "kind": "wallhole", "style": "attic", "mount": "face", "W": 2.25, "D": 0.35, "R": 0.12, "H": 3, "fit": "max", "uv1": true, "hole": [0.7, 0.5],
          "tris": 4000, "notes": "broken boards" },
      "Band_peel_A_wood": { "kind": "peel", "style": "wood", "mount": "wall", "W": 1.2, "D": 0.08, "H": 1.2, "z0": 0.4, "fit": "max", "tris": 1500,
          "notes": "curled wallpaper, textured both sides" },
      "Band_peel_B_wood": { "kind": "peel", "style": "wood", "mount": "wall", "W": 1.2, "D": 0.08, "H": 1.2, "z0": 0.4, "fit": "max", "tris": 1500,
          "notes": "curled wallpaper, textured both sides" },
      "Band_peel_C_wood": { "kind": "peel", "style": "wood", "mount": "wall", "W": 1.2, "D": 0.08, "H": 1.2, "z0": 0.4, "fit": "max", "tris": 1500,
          "notes": "curled wallpaper, textured both sides" },
      "Band_peel_D_wood": { "kind": "peel", "style": "wood", "mount": "wall", "W": 1.2, "D": 0.08, "H": 1.2, "z0": 0.4, "fit": "max", "tris": 1500,
          "notes": "curled wallpaper, textured both sides" },
      "Band_peel_A_tile": { "kind": "peel", "style": "tile", "mount": "wall", "W": 1.2, "D": 0.08, "H": 1.2, "z0": 0.4, "fit": "max", "tris": 1500,
          "notes": "curled wallpaper, textured both sides" },
      "Band_peel_B_tile": { "kind": "peel", "style": "tile", "mount": "wall", "W": 1.2, "D": 0.08, "H": 1.2, "z0": 0.4, "fit": "max", "tris": 1500,
          "notes": "curled wallpaper, textured both sides" },
      "Band_peel_C_tile": { "kind": "peel", "style": "tile", "mount": "wall", "W": 1.2, "D": 0.08, "H": 1.2, "z0": 0.4, "fit": "max", "tris": 1500,
          "notes": "curled wallpaper, textured both sides" },
      "Band_peel_D_tile": { "kind": "peel", "style": "tile", "mount": "wall", "W": 1.2, "D": 0.08, "H": 1.2, "z0": 0.4, "fit": "max", "tris": 1500,
          "notes": "curled wallpaper, textured both sides" },
      "Band_peel_A_concrete": { "kind": "peel", "style": "concrete", "mount": "wall", "W": 1.2, "D": 0.08, "H": 1.2, "z0": 0.4, "fit": "max", "tris": 1500,
          "notes": "flaking paint, textured both sides" },
      "Band_peel_B_concrete": { "kind": "peel", "style": "concrete", "mount": "wall", "W": 1.2, "D": 0.08, "H": 1.2, "z0": 0.4, "fit": "max", "tris": 1500,
          "notes": "flaking paint, textured both sides" },
      "Band_peel_C_concrete": { "kind": "peel", "style": "concrete", "mount": "wall", "W": 1.2, "D": 0.08, "H": 1.2, "z0": 0.4, "fit": "max", "tris": 1500,
          "notes": "flaking paint, textured both sides" },
      "Band_peel_D_concrete": { "kind": "peel", "style": "concrete", "mount": "wall", "W": 1.2, "D": 0.08, "H": 1.2, "z0": 0.4, "fit": "max", "tris": 1500,
          "notes": "flaking paint, textured both sides" },
      "Band_peel_A_attic": { "kind": "peel", "style": "attic", "mount": "wall", "W": 1.2, "D": 0.08, "H": 1.2, "z0": 0.4, "fit": "max", "tris": 1500,
          "notes": "split boards, textured both sides" },
      "Band_peel_B_attic": { "kind": "peel", "style": "attic", "mount": "wall", "W": 1.2, "D": 0.08, "H": 1.2, "z0": 0.4, "fit": "max", "tris": 1500,
          "notes": "split boards, textured both sides" },
      "Band_peel_C_attic": { "kind": "peel", "style": "attic", "mount": "wall", "W": 1.2, "D": 0.08, "H": 1.2, "z0": 0.4, "fit": "max", "tris": 1500,
          "notes": "split boards, textured both sides" },
      "Band_peel_D_attic": { "kind": "peel", "style": "attic", "mount": "wall", "W": 1.2, "D": 0.08, "H": 1.2, "z0": 0.4, "fit": "max", "tris": 1500,
          "notes": "split boards, textured both sides" },
      "Band_peel_A_workshop": { "kind": "peel", "style": "workshop", "mount": "wall", "W": 1.2, "D": 0.08, "H": 1.2, "z0": 0.4, "fit": "max", "tris": 1500,
          "notes": "flaking paint, textured both sides" },
      "Band_peel_B_workshop": { "kind": "peel", "style": "workshop", "mount": "wall", "W": 1.2, "D": 0.08, "H": 1.2, "z0": 0.4, "fit": "max", "tris": 1500,
          "notes": "flaking paint, textured both sides" },
      "Band_peel_C_workshop": { "kind": "peel", "style": "workshop", "mount": "wall", "W": 1.2, "D": 0.08, "H": 1.2, "z0": 0.4, "fit": "max", "tris": 1500,
          "notes": "flaking paint, textured both sides" },
      "Band_peel_D_workshop": { "kind": "peel", "style": "workshop", "mount": "wall", "W": 1.2, "D": 0.08, "H": 1.2, "z0": 0.4, "fit": "max", "tris": 1500,
          "notes": "flaking paint, textured both sides" },
      "Mod_niche_tile": { "kind": "niche", "style": "tile", "mount": "face", "W": 2.25, "D": 0.05, "R": 0.35, "H": 3, "fit": "max", "uv1": true, "niche": [0.6, 1.1, 0.35],
          "tris": 6000, "notes": "arched niche with a porcelain figure" },
      "Band_ceilingrose": { "kind": "ceilingrose", "style": "wood", "mount": "ceiling", "W": 0.6, "D": 0.6, "H": 0.08, "z0": -0.08, "fit": "max", "tris": 3000,
          "notes": "plaster rose" },
      "Band_coffer_rose": { "kind": "ceilingrose", "style": "tile", "mount": "ceiling", "W": 1.4, "D": 1.4, "H": 0.15, "z0": -0.15, "fit": "max", "tris": 3000,
          "notes": "coffer surround + rose" },
      "Mod_ceilhole_wood": { "kind": "ceilhole", "style": "wood", "mount": "ceiling", "W": 2.25, "D": 2.25, "H": 0.6, "z0": -0.3, "fit": "max", "uv1": true, "tris": 4000,
          "notes": "hanging lath no lower than 2.40 m" },
      "Mod_ceilhole_concrete": { "kind": "ceilhole", "style": "concrete", "mount": "ceiling", "W": 2.25, "D": 2.25, "H": 0.6, "z0": -0.3, "fit": "max", "uv1": true, "tris": 4000,
          "notes": "hanging lath no lower than 2.40 m" },
      "Mod_ceilhole_attic": { "kind": "ceilhole", "style": "attic", "mount": "ceiling", "W": 2.25, "D": 2.25, "H": 0.6, "z0": -0.3, "fit": "max", "uv1": true, "tris": 4000,
          "notes": "hanging lath no lower than 2.40 m" },
      "Mod_ceilhole_workshop": { "kind": "ceilhole", "style": "workshop", "mount": "ceiling", "W": 2.25, "D": 2.25, "H": 0.6, "z0": -0.3, "fit": "max", "uv1": true, "tris": 4000,
          "notes": "hanging lath no lower than 2.40 m" },
      "Band_attic_ladder": { "kind": "attic_ladder", "style": "attic", "mount": "ceiling", "W": 0.7, "D": 1.2, "H": 0.12, "z0": -0.12, "fit": "max", "tris": 3000,
          "notes": "loft ladder folded into a ceiling hatch" }
    } },
  "wardrobes": {
    "Ward_body_wood": { "part": "body", "style": "wood", "W": 1.25, "D": 0.66, "H": 2.35, "fit": "max", "body": [1.15, 0.6, 2.25], "clearX": 0.3, "tris": 8000,
        "notes": "painted pine with nursery stencils; open front, hollow single-sided interior" },
    "Ward_leafL_wood": { "part": "leaf", "style": "wood", "W": 0.575, "D": 0.03, "H": 2.2, "fit": "max", "hinge": [-0.575, -0.305, 0.025], "tris": 1500,
        "notes": "leaf along +x to the middle; alpha-tested louvres" },
    "Ward_leafR_wood": { "part": "leaf", "style": "wood", "W": 0.575, "D": 0.03, "H": 2.2, "fit": "max", "hinge": [0.575, -0.305, 0.025], "tris": 1500,
        "notes": "leaf along -x to the middle; alpha-tested louvres" },
    "Ward_body_tile": { "part": "body", "style": "tile", "W": 1.25, "D": 0.66, "H": 2.35, "fit": "max", "body": [1.15, 0.6, 2.25], "clearX": 0.3, "tris": 8000,
        "notes": "mahogany armoire; open front, hollow single-sided interior" },
    "Ward_leafL_tile": { "part": "leaf", "style": "tile", "W": 0.575, "D": 0.03, "H": 2.2, "fit": "max", "hinge": [-0.575, -0.305, 0.025], "tris": 1500,
        "notes": "leaf along +x to the middle; alpha-tested louvres" },
    "Ward_leafR_tile": { "part": "leaf", "style": "tile", "W": 0.575, "D": 0.03, "H": 2.2, "fit": "max", "hinge": [0.575, -0.305, 0.025], "tris": 1500,
        "notes": "leaf along -x to the middle; alpha-tested louvres" },
    "Ward_body_concrete": { "part": "body", "style": "concrete", "W": 1.25, "D": 0.66, "H": 2.35, "fit": "max", "body": [1.15, 0.6, 2.25], "clearX": 0.3, "tris": 8000,
        "notes": "double steel locker, louvred; open front, hollow single-sided interior" },
    "Ward_leafL_concrete": { "part": "leaf", "style": "concrete", "W": 0.575, "D": 0.03, "H": 2.2, "fit": "max", "hinge": [-0.575, -0.305, 0.025], "tris": 1500,
        "notes": "leaf along +x to the middle; alpha-tested louvres" },
    "Ward_leafR_concrete": { "part": "leaf", "style": "concrete", "W": 0.575, "D": 0.03, "H": 2.2, "fit": "max", "hinge": [0.575, -0.305, 0.025], "tris": 1500,
        "notes": "leaf along -x to the middle; alpha-tested louvres" },
    "Ward_body_attic": { "part": "body", "style": "attic", "W": 1.25, "D": 0.66, "H": 2.35, "fit": "max", "body": [1.15, 0.6, 2.25], "clearX": 0.3, "tris": 8000,
        "notes": "wardrobe half under a dust sheet; open front, hollow single-sided interior" },
    "Ward_leafL_attic": { "part": "leaf", "style": "attic", "W": 0.575, "D": 0.03, "H": 2.2, "fit": "max", "hinge": [-0.575, -0.305, 0.025], "tris": 1500,
        "notes": "leaf along +x to the middle; alpha-tested louvres" },
    "Ward_leafR_attic": { "part": "leaf", "style": "attic", "W": 0.575, "D": 0.03, "H": 2.2, "fit": "max", "hinge": [0.575, -0.305, 0.025], "tris": 1500,
        "notes": "leaf along -x to the middle; alpha-tested louvres" },
    "Ward_body_workshop": { "part": "body", "style": "workshop", "W": 1.25, "D": 0.66, "H": 2.35, "fit": "max", "body": [1.15, 0.6, 2.25], "clearX": 0.3, "tris": 8000,
        "notes": "louvred tool cupboard; open front, hollow single-sided interior" },
    "Ward_leafL_workshop": { "part": "leaf", "style": "workshop", "W": 0.575, "D": 0.03, "H": 2.2, "fit": "max", "hinge": [-0.575, -0.305, 0.025], "tris": 1500,
        "notes": "leaf along +x to the middle; alpha-tested louvres" },
    "Ward_leafR_workshop": { "part": "leaf", "style": "workshop", "W": 0.575, "D": 0.03, "H": 2.2, "fit": "max", "hinge": [0.575, -0.305, 0.025], "tris": 1500,
        "notes": "leaf along -x to the middle; alpha-tested louvres" }
  }
}/*END*/;
