// (positions are in world units; a tile is 50 units, the start room is tiles 1..3)
// Multiplayer: lobby (code, full, kick, nametags, ready), then the shared game (spawn, fuses, blocking, down/revive, wardrobes, floors, game over, leaving).
import { launch, player, check, summary, visible, text, until, openMp, OUT, click, fill } from './lib.mjs';
const b = await launch();
console.log('== lobby');
const A = await player(b, 'Alice', 800, 450), B = await player(b, 'Bob'), C = await player(b, 'Cara'), D = await player(b, 'Dan');
await openMp(A); await click(A, '#mpCreate');
check(await until(A, () => !document.getElementById('lobby').classList.contains('hidden')), 'host sees the lobby screen');
const code = (await text(A, 'lbCode')).replace(/\s/g, '');
check(/^\d{6}$/.test(code), 'lobby code is 6 digits', code);
for (const P of [B, C, D]) { await openMp(P); await fill(P, '#mpCode', code); await click(P, '#mpJoin');
  // (90 s: with four browsers drawing on this test machine's CPU, the last page can be starved for half a minute; its own timers stall too)
  check(await until(P, () => !document.getElementById('lobby').classList.contains('hidden'), null, 90000), P.pname + ' joined'); }
check(await until(A, () => document.querySelectorAll('#lbList li:not(.empty)').length === 4), 'host lists 4 players');
const names = await D.evaluate(() => [...document.querySelectorAll('#lbList li:not(.empty) .nm')].map(e => e.textContent));
check(names.some(n => n.includes('Alice')) && names.some(n => n.includes('Dan')), 'a joiner sees everyone by name', names);
await A.screenshot({ timeout: 120000, path: OUT + '/lobby_host.png' });
console.log('== full lobby');
const E = await player(b, 'Eve'); await openMp(E); await fill(E, '#mpCode', code); await click(E, '#mpJoin');
check(await until(E, () => /full/i.test(document.getElementById('mpStatus').textContent)), '5th player is told the lobby is full', await text(E, 'mpStatus'));
await E.context().close();
console.log('== kick');
const kicked = await A.evaluate(() => { const li = [...document.querySelectorAll('#lbList li')].find(l => l.textContent.includes('Dan')); const k = li && li.querySelector('.kick'); if (k) k.click(); return !!k; });
check(kicked, 'host has a kick button for Dan');
check(await until(D, () => /removed/i.test(document.getElementById('mpStatus').textContent)), 'Dan is back at the menu, told he was removed', await text(D, 'mpStatus'));
check(await until(A, () => document.querySelectorAll('#lbList li:not(.empty)').length === 3), 'host lists 3 players after the kick');
await D.context().close();
check(await until(B, () => document.querySelectorAll('#lbList li:not(.empty)').length === 3), 'others see the kick too');
check(!(await B.evaluate(() => !!document.querySelector('#lbList .kick'))), 'a non-owner has no kick buttons');
console.log('== nametag');
await fill(B, '#lbName', 'Bobby');
check(await until(A, () => [...document.querySelectorAll('#lbList .nm')].some(e => e.textContent.includes('Bobby'))), 'host sees the new nametag "Bobby"');
check(await until(C, () => [...document.querySelectorAll('#lbList .nm')].some(e => e.textContent.includes('Bobby'))), 'others see "Bobby" too');
console.log('== ready up');
await click(A, '#lbReady'); await click(B, '#lbReady');
await A.waitForTimeout(4500);
check(await A.evaluate(() => bb.state) === 'lobby', 'no start while Cara is not ready');
check(/2 of 3 ready/.test(await text(C, 'lbStatus')), 'status shows 2 of 3 ready', await text(C, 'lbStatus'));
await click(C, '#lbReady');
check(await until(C, () => /Starting in/.test(document.getElementById('lbStatus').textContent), null, 5000), 'countdown starts when everyone is ready');
const started = await Promise.all([A, B, C].map(P => until(P, () => bb.state === 'play' && bb.MP.inGame, null, 20000)));
check(started.every(Boolean), 'the game starts for all 3 players', started);
const grids = await Promise.all([A, B, C].map(P => P.evaluate(() => bb.grid.map(r => r.join('')).join('|'))));
check(grids[0] === grids[1] && grids[1] === grids[2], 'everyone got the same house');
const pos = await Promise.all([A, B, C].map(P => P.evaluate(() => [bb.player.x, bb.player.y])));
check(pos.every(([x, y]) => x > 50 && x < 200 && y > 50 && y < 200), 'everyone spawned in the start room', pos);
const dmin = Math.min(...[[0, 1], [0, 2], [1, 2]].map(([i, j]) => Math.hypot(pos[i][0] - pos[j][0], pos[i][1] - pos[j][1])));
check(dmin >= 22, 'nobody spawned inside someone else', dmin);
const fz = await A.evaluate(() => bb.fuses.length), fzB = await B.evaluate(() => bb.fuses.length);
check(fz === 5 && fzB === 5, '3 players: 5 fuses on floor 1 (3 + 2 extra)', [fz, fzB]);

// ---------------- in the game ----------------
const ids = await A.evaluate(() => ({ A: bb.MP.myId, others: [...bb.MP.others.values()].map(o => [o.name, o.id]) }));
const idOf = n => (ids.others.find(o => o[0].startsWith(n)) || [])[1];
const Bid = idOf('Bob'), Cid = idOf('Cara');
const freeze = () => A.evaluate(() => { bb.monster.active = false; bb.monster.spawnT = 1e9; });
await freeze();
console.log('== teammates');
check(await A.evaluate(() => [...bb.MP.others.values()].every(o => o.av && o.av.human)), 'teammates are human figures (not the simple stand-in)');
for (const P of [A, B, C]) check(await P.evaluate(() => [...bb.MP.others.values()].filter(o => o.av && o.av.obj.parent).length === 2), P.pname + ' sees 2 teammate figures in the world');
// Alice looks at the other two and takes a picture
await A.evaluate(() => { const o = [...bb.MP.others.values()]; const mx = (o[0].x + o[1].x) / 2, my = (o[0].y + o[1].y) / 2;
  bb.player.x = 75; bb.player.y = 125; bb.player.ang = Math.atan2(my - 125, mx - 75); bb.player.pitch = -0.05; });
await B.evaluate(() => { bb.player.x = 175; bb.player.y = 81; bb.player.ang = Math.PI; });
await C.evaluate(() => { bb.player.x = 181; bb.player.y = 175; bb.player.ang = Math.PI * 0.9; });
await until(A, () => [...bb.MP.others.values()].every(o => Math.hypot(o.x - o.tx, o.y - o.ty) < 3), null, 20000); await A.waitForTimeout(1500); await A.screenshot({ timeout: 120000, path: OUT + '/game_teammates.png' });
const seen = await A.evaluate(() => [...bb.MP.others.values()].map(o => [o.name, Math.round(o.x), Math.round(o.y)]));
check(seen.some(([n, x, y]) => n.startsWith('Bob') && Math.abs(x - 175) < 6 && Math.abs(y - 81) < 6), "the host sees Bobby where Bobby's own game says he is", seen);
console.log('== her position is the same for everyone');
await A.evaluate(() => { const m = bb.monster; m.active = true; m.spawnT = 0; m.state = 'wander'; m.target = null; });
await until(B, () => bb.monster.active, null, 30000); await A.waitForTimeout(2000);
const [mA, mB] = await Promise.all([A.evaluate(() => [bb.monster.x, bb.monster.y]), B.evaluate(() => [bb.monster.x, bb.monster.y, bb.monster.active])]);
check(mB[2] && Math.hypot(mA[0] - mB[0], mA[1] - mB[1]) < 40, 'a joiner sees her at the host\'s position', { mA, mB });
await freeze();
console.log('== body blocking');
await B.evaluate(() => { bb.player.x = 175; bb.player.y = 125; });
await C.evaluate(() => { bb.player.x = 75; bb.player.y = 181; });
await A.evaluate(() => { bb.player.x = 75; bb.player.y = 125; bb.player.ang = 0; bb.player.pitch = 0; });
await A.waitForTimeout(1500);
await A.keyboard.down('KeyW'); await A.waitForTimeout(4000); await A.keyboard.up('KeyW');
const blk = await A.evaluate(() => { const o = [...bb.MP.others.values()].find(q => q.name.startsWith('Bob')); return [bb.player.x, bb.player.y, o.x, o.y]; });
const dBlk = Math.hypot(blk[0] - blk[2], blk[1] - blk[3]);
check(blk[0] > 95, 'Alice walked towards Bobby', blk);   // (from x = 75; on a slow test machine she covers less ground in 4 s)
check(dBlk >= 20, 'Alice stopped at Bobby instead of walking through him (distance ' + dBlk.toFixed(1) + ')', blk);
console.log('== one person per wardrobe');
const cl = await A.evaluate(() => { const c = bb.closets[0]; return { x: c.x + c.ox * 10, y: c.y + c.oy * 10, ang: Math.atan2(-c.oy, -c.ox) }; });
const goTo = (P, q) => P.evaluate(q => { bb.player.x = q.x; bb.player.y = q.y; bb.player.ang = q.ang; }, q);
await goTo(B, cl); await B.waitForTimeout(1500); await B.keyboard.press('KeyE');
await until(B, () => !!document.querySelector('#hide:not(.hidden)'), null, 20000);
if (!(await B.evaluate(() => bb.player.hidden))) await B.keyboard.press('KeyE');
check(await until(B, () => bb.player.hidden, null, 20000), 'Bobby hides in the wardrobe');
await until(C, () => [...bb.MP.others.values()].some(o => o.hidden), null, 20000);
await A.waitForTimeout(1000);
await goTo(C, cl); await until(C, () => !!document.querySelector('#hide:not(.hidden)'), null, 20000); await C.keyboard.press('KeyE'); await until(C, () => /locked/i.test(document.getElementById('msg').textContent), null, 15000);
check(!(await C.evaluate(() => bb.player.hidden)), 'Cara can not get into the same wardrobe');
check(/locked/i.test(await text(C, 'msg')), 'Cara is told it is locked', await text(C, 'msg'));
await B.keyboard.press('KeyE'); await until(B, () => !bb.player.hidden, null, 15000);
await until(C, () => [...bb.MP.others.values()].every(o => !o.hidden), null, 20000);
await goTo(C, cl); await until(C, () => !!document.querySelector('#hide:not(.hidden)'), null, 20000); await C.keyboard.press('KeyE');
check(await until(C, () => bb.player.hidden, null, 20000), 'once Bobby is out, Cara can hide there');
await C.keyboard.press('KeyE'); await until(C, () => !bb.player.hidden, null, 15000); await until(B, () => [...bb.MP.others.values()].every(o => !o.hidden), null, 20000);
// both at the same moment: the host lets exactly one of them in
await goTo(B, cl); await goTo(C, cl); await B.waitForTimeout(1500);
await Promise.all([B.evaluate(() => bb.toggleHide()), C.evaluate(() => bb.toggleHide())]);
await until(B, () => true, null, 1000);
const settled = await Promise.all([B, C].map(P => until(P, () => false, null, 1).then(() => 0)));
await B.waitForTimeout(1000);
for (let i = 0; i < 40; i++) { const hs = await Promise.all([B, C].map(P => P.evaluate(() => bb.player.hidden))); if (hs.filter(Boolean).length <= 1) break; await B.waitForTimeout(500); }
const both = await Promise.all([B, C].map(P => P.evaluate(() => bb.player.hidden)));
check(both.filter(Boolean).length === 1, 'two players hiding at the same moment: only one stays inside', both);
for (const P of [B, C]) await P.evaluate(() => { if (bb.player.hidden) bb.toggleHide(); });
console.log('== down and revive');
await B.evaluate(() => { bb.player.x = 125; bb.player.y = 125; });
await C.evaluate(() => { bb.player.x = 75; bb.player.y = 75; });
await A.evaluate(() => { bb.player.x = 187; bb.player.y = 187; bb.player.ang = Math.PI * 1.25; });
await A.waitForTimeout(1500);
await A.evaluate(id => bb.downPlayer({ id }, 'test'), Bid);
check(await until(B, () => bb.player.down, null, 8000), 'Bobby goes down on his own screen');
check(await until(C, () => [...bb.MP.others.values()].some(o => o.name.startsWith('Bob') && o.down), null, 8000), 'Cara sees Bobby down');
check(await until(B, () => !document.getElementById('downMsg').classList.contains('hidden') && /down/i.test(document.getElementById('downMsg').textContent), null, 30000), 'Bobby sees the "You\'re down" countdown', await text(B, 'downMsg'));
const dl1 = await B.evaluate(() => bb.player.downLeft); await B.waitForTimeout(3000); const dl2 = await B.evaluate(() => bb.player.downLeft);
check(dl1 <= 50 && dl2 < dl1, 'the 50 second clock is running', [dl1, dl2]);
await A.evaluate(() => { bb.player.ang = 0.8; });            // facing away from Bobby, so the arrow points behind
await A.waitForTimeout(1500); await A.screenshot({ timeout: 120000, path: OUT + '/game_indicator.png' });
await B.screenshot({ timeout: 120000, path: OUT + '/game_down.png' });
check(!(await visible(A, 'revive')), 'Alice is too far away to revive');
await C.evaluate(() => { bb.player.x = 100; bb.player.y = 125; bb.player.ang = 0; });
check(await until(C, () => !!bb.reviveTarget, null, 8000), 'Cara next to Bobby gets the revive prompt');
await C.keyboard.down('KeyE');
await C.waitForTimeout(1500); await C.screenshot({ timeout: 120000, path: OUT + '/game_reviving.png' });
check(await until(B, () => !bb.player.down, null, 60000), 'holding E, Cara revives Bobby');
await C.keyboard.up('KeyE');
check(await until(A, () => [...bb.MP.others.values()].every(o => !o.down), null, 8000), 'the host sees Bobby back up');
console.log('== bleeding out');
await A.evaluate(id => bb.downPlayer({ id }, 'test'), Cid);
await until(A, () => [...bb.MP.others.values()].some(o => o.name.startsWith('Cara') && o.down), null, 8000);
await A.evaluate(() => { const o = [...bb.MP.others.values()].find(q => q.name.startsWith('Cara')); o.downLeft = 0.2; });
check(await until(C, () => bb.player.dead, null, 15000), 'after the clock runs out Cara is out');
check(await until(C, () => /make it/.test(document.getElementById('downMsg').textContent), null, 30000), 'Cara sees "You didn\'t make it" and watches a teammate', await text(C, 'downMsg'));
await C.waitForTimeout(1000); await C.screenshot({ timeout: 120000, path: OUT + '/game_spectate.png' });
console.log('== fuses are shared');
const f0 = await A.evaluate(() => { const f = bb.fuses[0]; return { x: f.x, y: f.y, ang: 0 }; });
await goTo(B, f0);
check((await Promise.all([A, B, C].map(P => until(P, () => bb.fusesGot === 1 && bb.fuses[0].got, null, 10000)))).every(Boolean), 'Bobby picks up a fuse: everyone has 1 fuse');
console.log('== the next floor, together');
await A.evaluate(() => bb.fuses.forEach((f, k) => { if (!f.got) bb.hostEmit({ t: 'fuseGot', k, by: bb.MP.myId }); }));
check((await Promise.all([A, B, C].map(P => until(P, () => bb.powerOn, null, 10000)))).every(Boolean), 'all fuses in: the door unlocks for everyone');
await freeze();
const ex = await A.evaluate(() => ({ x: bb.exit.x, y: bb.exit.y, ang: 0 }));
await goTo(B, ex);
check((await Promise.all([A, B, C].map(P => until(P, () => bb.state === 'trans', null, 10000)))).every(Boolean), 'Bobby reaches the door: everyone sees the next floor screen');
check((await Promise.all([A, B, C].map(P => until(P, () => bb.state === 'play' && bb.floorIdx === 1, null, 30000)))).every(Boolean), 'everyone is on floor 2');
check(!(await C.evaluate(() => bb.player.dead || bb.player.down)), 'Cara is back on the new floor');
const g2 = await Promise.all([A, B, C].map(P => P.evaluate(() => bb.grid.map(r => r.join('')).join('|'))));
check(g2[0] === g2[1] && g2[1] === g2[2], 'floor 2 is the same house for everyone');
console.log('== game over');
await freeze();
for (const id of [ids.A, Bid, Cid]) { await A.evaluate(id => bb.downPlayer({ id }, 'test'), id); await A.waitForTimeout(300); }
check((await Promise.all([A, B, C].map(P => until(P, () => !document.getElementById('dead').classList.contains('hidden') && /EVERYONE/.test(document.getElementById('dTitle').textContent), null, 30000)))).every(Boolean), 'everyone down: "SHE GOT EVERYONE" for all');
await B.screenshot({ timeout: 120000, path: OUT + '/game_over.png' });
await click(B, '#retry');
check(await until(B, () => !document.getElementById('lobby').classList.contains('hidden') && /0 of 3 ready/.test(document.getElementById('lbStatus').textContent), null, 10000), 'back in the lobby, nobody is ready yet', await text(B, 'lbStatus'));
console.log('== leaving');
await click(A, '#retry'); await click(C, '#retry');
await click(C, '#lbLeave');
check(await until(A, () => document.querySelectorAll('#lbList li:not(.empty)').length === 2, null, 10000), 'Cara leaves: the host lists 2 players');
await click(A, '#lbLeave');
check(await until(B, () => /closed the lobby|Lost the connection/.test(document.getElementById('mpStatus').textContent), null, 20000), 'the host leaves: Bobby is told and back at the menu', await text(B, 'mpStatus'));
process.exitCode = summary();
await b.close();
