// Single player: a full run through the main features.
import { launch, solo, check, summary, until, click, text, startSolo } from './lib.mjs';
const b = await launch();
const p = await solo(b);
console.log('== single player still works');
await startSolo(p);
check(await until(p, () => bb.state === 'play'), 'the game starts');
check(await p.evaluate(() => bb.fuses.length === 3 && !bb.MP.on && Math.abs(bb.player.x - bb.T * 1.5) < 1), '3 fuses, start tile, no multiplayer');
await p.evaluate(() => { bb.monster.active = false; bb.monster.spawnT = 1e9; });
const f = await p.evaluate(() => [bb.fuses[0].x, bb.fuses[0].y]);
await p.evaluate(f => { bb.player.x = f[0]; bb.player.y = f[1]; }, f);
check(await until(p, () => bb.fusesGot === 1), 'picking up a fuse');
await p.evaluate(() => { for (const f of bb.fuses) { bb.player.x = f.x; bb.player.y = f.y; } });
await p.evaluate(() => bb.fuses.forEach((f, k) => bb.applyFuse(k)));
check(await until(p, () => bb.powerOn), 'all fuses: power on');
await p.evaluate(() => { bb.monster.active = false; bb.monster.spawnT = 1e9; bb.player.x = bb.exit.x; bb.player.y = bb.exit.y; });
check(await until(p, () => bb.state === 'trans'), 'reaching the door: next floor screen');
await click(p, '#tGo');
check(await until(p, () => bb.state === 'play' && bb.floorIdx === 1), 'floor 2');
await p.evaluate(() => { const c = bb.closets[0]; bb.player.x = c.x + c.ox * 10; bb.player.y = c.y + c.oy * 10; bb.monster.active = false; bb.sceneCool = 999; });
await until(p, () => !!document.querySelector('#hide:not(.hidden)'), null, 15000);
await p.keyboard.press('KeyE'); check(await until(p, () => bb.player.hidden), 'hiding in a wardrobe');
await p.keyboard.press('KeyE'); check(await until(p, () => !bb.player.hidden), 'leaving the wardrobe');
await p.keyboard.down('KeyW'); await p.waitForTimeout(1500); await p.keyboard.up('KeyW');
await p.evaluate(() => { const c = bb.closets[0]; bb.player.x = c.x + c.ox * 10; bb.player.y = c.y + c.oy * 10; const far = bb.CELLS().map(bb.center).sort((a, b) => Math.hypot(b.x - c.x, b.y - c.y) - Math.hypot(a.x - c.x, a.y - c.y))[0]; bb.monster.active = true; bb.monster.state = 'wander'; bb.monster.x = far.x; bb.monster.y = far.y; bb.sceneCool = 0; });
await until(p, () => !!document.querySelector('#hide:not(.hidden)'), null, 15000);
await p.keyboard.press('KeyE');
check(await until(p, () => !!bb.closetScene, null, 5000), 'the wardrobe scene starts when hiding while she is around');
await p.evaluate(() => { bb.closetScene = null; bb.toggleHide(); });
await p.evaluate(() => { const m = bb.monster; m.active = true; m.spawnT = 0; m.x = bb.player.x + 30 * Math.cos(bb.player.ang); m.y = bb.player.y + 30 * Math.sin(bb.player.ang); m.screamT = 0; });
check(await until(p, () => bb.state === 'dead', null, 20000), 'she catches you: game over');
check(await until(p, () => !document.getElementById('dead').classList.contains('hidden'), null, 60000), 'the "SHE GOT YOU" screen', await text(p, 'dTitle'));
check(/SHE GOT YOU/.test(await text(p, 'dTitle')) && /Try again/.test(await text(p, 'retry')), 'single player words on the death screen');
await click(p, '#retry');
check(await until(p, () => bb.state === 'play' && bb.floorIdx === 1), 'Try again restarts the floor');
process.exitCode = summary(); await b.close();
